//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Users.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class User
    {

       public User()
            {
                Users_PK = Guid.NewGuid();
            }
        public System.Guid Users_PK { get; set; }
        [DisplayName("FirstName")]
        public string Fname { get; set; }
        public string Mname { get; set; }
        public string Lname { get; set; }
        public System.DateTime DOB { get; set; }
       
        [DataType(DataType.PhoneNumber)]
        public string Mobile_No { get; set; }
        public string LandLine_No { get; set; }
        public string FAX { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage ="enter email address")]
        [Index(IsUnique = true)]

        //   [Remote("IsEmailExist", "UserMvc", ErrorMessage = "Email already exists!")]

        public string Email { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please Enter Password")]
        [Display(Name = "Password")]
        public string Password { get; set; }
        [Display(Name="Gender")]
        public string Gender { get; set; }
        
        public string User_Address { get; set; }
    }
}
